import { build } from "esbuild";
import { readFile } from "node:fs/promises";
import { relative, resolve } from "node:path";

const projectRoot = process.cwd();

const rawTextPlugin = {
  name: "raw-text",
  setup(build) {
    build.onResolve({ filter: /\?raw$/ }, (args) => {
      const absolutePath = resolve(args.resolveDir, args.path.replace(/\?raw$/, ""));
      return {
        path: relative(projectRoot, absolutePath).split("\\").join("/"),
        namespace: "raw-text",
        pluginData: { absolutePath },
      };
    });
    build.onLoad({ filter: /.*/, namespace: "raw-text" }, async (args) => ({
      contents: await readFile(args.pluginData.absolutePath, "utf8"),
      loader: "text",
    }));
  },
};

const entries = [
  "capture",
  "cloudflare-proxy",
  "context",
  "feedback",
  "prompt",
  "provider",
  "publish",
  "react",
];

await Promise.all(
  entries.map((entry) =>
    build({
      entryPoints: [`src/${entry}.ts`],
      outfile: `dist/${entry}.js`,
      bundle: true,
      platform: "node",
      format: "esm",
      target: "node20",
      plugins: [rawTextPlugin],
      sourcemap: false,
      minify: false,
      banner: {
        js: [
          "// Generated by npm run build. Do not edit.",
          'import { createRequire as __slashCodexCreateRequire } from "node:module";',
          "const require = __slashCodexCreateRequire(import.meta.url);",
        ].join("\n"),
      },
    }),
  ),
);
