import { build } from "esbuild";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const rawTextPlugin = {
  name: "raw-text",
  setup(build) {
    build.onResolve({ filter: /\?raw$/ }, (args) => ({
      path: resolve(args.resolveDir, args.path.replace(/\?raw$/, "")),
      namespace: "raw-text",
    }));
    build.onLoad({ filter: /.*/, namespace: "raw-text" }, async (args) => ({
      contents: await readFile(args.path, "utf8"),
      loader: "text",
    }));
  },
};

const entries = [
  "capture",
  "cloudflare-proxy",
  "context",
  "feedback",
  "prompt",
  "provider",
  "publish",
  "react",
];

await Promise.all(
  entries.map((entry) =>
    build({
      entryPoints: [`src/${entry}.ts`],
      outfile: `dist/${entry}.js`,
      bundle: true,
      platform: "node",
      format: "esm",
      target: "node20",
      plugins: [rawTextPlugin],
      sourcemap: false,
      minify: false,
      banner: { js: "// Generated by npm run build. Do not edit." },
    }),
  ),
);
